### ISSUE TITLE
[issue]: Invalid image, Failed to read header: Unsupported, Failed to load image: Unsupported, start_image() returned Unsupported

### ISSUE THREAD

**Issue by kerbless** [ventoy/Ventoy#1735]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.78

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

UEFI Mode

### Partition Style

MBR

### Disk Capacity

64GB

### Disk Manufacturer

EAGET

### What happened?

When trying to boot Ventoy I get the following:
![image](https://user-images.githubusercontent.com/32358946/179207119-d5f87aeb-878d-419c-88f6-7707fb713c39.png)

**Comment by kerbless** [comment]
![image](https://user-images.githubusercontent.com/32358946/179207319-8b167ff8-6e6f-4e63-a711-ead3ead99b45.png)

**Comment by ventoy** [comment]
#1718 https://github.com/ventoy/Ventoy/issues/1707

**Comment by kerbless** [comment]
I tried to use Ventoy 1.0.77 on the same hardware and it works (only without secure boot).

**Comment by Lebsasha** [comment]
I have the same issue with Ventoy 1.0.78 with UEFI BIOS in normal mode, but with same BIOS in CSM mode version 1.0.78 works

**Comment by ventoy** [comment]
Ventoy 1.0.79 rollback the Super-UEFIinSecureBoot-Disk to v3.3 and should have no such problem.

**Comment by Lebsasha** [comment]
Yes, I try Ventoy 1.0.79 and it become booting nicely. Thank you very much!

**Comment by msva** [comment]
Hi there!

I've similar issue with 1.0.93, although there is mentioned above (and in similar issues) that problem was already fixed :man_shrugging: 

Is it somethinng I am doing wrong?


Although, I'm trying it on IA32 UEFI (with secureboot **disabled**)

**Comment by steve6375** [comment]
I don't have a UEFI32 system, but Virtual Box UEFI32-boots the latest Ventoy 1.0.93 USB OK
![image](https://github.com/ventoy/Ventoy/assets/1469350/6c292024-58c7-4b94-ad45-c736309453f1)

Your FAT 32MB VTOYEFI partition should contain a \EFI\BOOT\BOOTIA32.EFI file. 
![image](https://github.com/ventoy/Ventoy/assets/1469350/ec671670-3fe2-4d16-b362-e861a8489d11)
This is the UEFI32 main boot file, so any 'good' UEFI32 BIOS should see this and boot to it IF you have disabled Secure Boot in your BIOS.

1. What Ventoy secure boot and GPT options did you test
2. Is Secure Boot disabled in your BIOS settings

**Comment by msva** [comment]
Unfortunately, I've already return the device I tested ventoy on to the owner, but:
1) there was disabled secureboot,
2) bootia32.efi was in place,
3) actually, I had installed ventoy in default mode (without `-g` key on `Ventoy2Disk.sh`, ust with `-i /dev/sdX`). Maybe this is the case, but why it blamed "headers", and not just "doesn't work"?...
4) (not sure if relevant in any way) "alpine x86" and "debian 12 amd64" lives was booted succesfully (both had grub as `bootia32.efi`)

**Comment by maaaaz** [comment]
This bug still lives on.

On a same laptop, the version `1.0.98` works without displaying (hence encountering ?) this message, while the currently latest `1.1.05` shows this error message.

**Comment by lemmings189** [comment]
Same error on 1.1.10

**Comment by cjlindem** [comment]
> I tried to use Ventoy 1.0.77 on the same hardware and it works (only without secure boot). I hope this is insightful, if you want you can close the issue.

I've just discovered Ventoy and my first use-case for it was on an old Intel Bay Trail PC which has a 64-bit processor and 32-bit UEFI BIOS with no Legacy option.

Using the latest version, 1.1.10, I received the Invalid Image error.  The same error as shown by the original poster.  Same issue on v1.0.98.  Finally, I tried 1.0.77 which worked fine.

**Comment by lemmings189** [comment]
> > I tried to use Ventoy 1.0.77 on the same hardware and it works (only without secure boot). I hope this is insightful, if you want you can close the issue.
> 
> I've just discovered Ventoy and my first use-case for it was on an old Intel Bay Trail PC which has a 64-bit processor and 32-bit UEFI BIOS with no Legacy option.
> 
> Using the latest version, 1.1.10, I received the Invalid Image error. The same error as shown by the original poster. Same issue on v1.0.98. Finally, I tried 1.0.77 which worked fine.

1.0.79 works fine for me

**Comment by ywjkid** [comment]
Concur.  1.0.79 works for me.  The latest version gave me the same error message.
