### ISSUE TITLE
[issue]: Flashing Cursor Hang On Old Laptops and Wimboot "Overflow is detected" error.

### ISSUE THREAD

**Issue by JohnTravolski** [ventoy/Ventoy#1777]
### Official FAQ

- [X] I have checked the official FAQ.

### Ventoy Version

1.0.79

### What about latest release

Yes. I have tried the latest release, but the bug still exist.

### BIOS Mode

Legacy BIOS Mode

### Partition Style

MBR

### Disk Capacity

500GB

### Disk Manufacturer

Inland

### What happened?

When I select either `en-us_windows_10_iot_enterprise_ltsc_2021_x64_dvd_257ad90f.iso` or `en_windows_10_enterprise_2016_ltsb_x64_dvd_9059483.iso` from Ventoy on two old "Legacy" BIOS laptops, rather than booting into the image, I get a black screen with a blinking cursor in the top left. It just stays there forever and never loads anything.

I have not had this issue on any UEFI laptops, those just load the Windows installer immediately A-OK. However, I do have one laptop with a legacy mode BIOS that starts the flashing cursor but eventually loads the image after about one minute. It's only the other two legacy laptops that never load it (even after waiting hours).

On those two legacy laptops, I tried Wimboot mode (`ctrl + w`), but I get an error stating:

`error: overflow is detected. Loading files......   xx%`

Once it reaches 100% it does successfully load the Windows installer and I can proceed.

Does anybody know why I get the hanging cursor in the first case and why Winboot has an overflow error in the second case?

**Comment by ventoy** [comment]
What happen if you press `ctrl+i` firstly and then select the ISO file to boot.

**Comment by JohnTravolski** [comment]
> What happen if you press `ctrl+i` firstly and then select the ISO file to boot.

It works! It is still slow (I get the blinking cursor for about 60 to 120 seconds before the ISO loads), but it does load the Windows ISO eventually on both machines.

**Do you know why it is so slow on all the legacy bios laptops?** One to two minutes isn't that long of a wait, but it's a fair bit slower when comparing it to being essentially instantaneous on all the machines with a UEFI bios.

**Comment by lmcorr** [comment]
I'm having the same issue. `ctrl+w` to wimboot, get `error: overflow is detected` `Loading files..... 100%` then hangs. 

`ctrl+i` to compatibility mode asks for nonexistent drivers, can't continue with installation. 

If I'm lucky wimboot mode may get to installation, then I get stuck on the partition screen. I have `Drive 0 Unallocated Space 111.8GB` but can't select and click next - `We couldn't create a new partition or locate an existing one. For more information, see the Setup log files.`

**Comment by steve6375** [comment]
We couldn't create a new partition or locate an existing one. For more information, see the Setup log files.
Did you check the log files?
SHIFT+F10
cd \windows\panther
dir *.log

Maybe Drive 0 is not correct? Should be GPT if UEFI boot or MBR if legacy boot.
Try DISKPART  and select drive 0 and type CLEAN maybe?

**Comment by lmcorr** [comment]
`Directory of X:\Windows\panther`
`28/08/2022 07:43 1,146 setuperri.log`
`28/08/2022 07:43 185,248 setupact.log`
`2 Files(s) 186,394 bytes`
`0 Dir(s) 527,237,120 bytes free`

In `diskpart` then `list disk` I have

`Disk #  Status   Size         Free   Dyn   Gpt`
`Disk 0 Online 111 GB 111 GB`
`Disk 1 Online  28 GB 0 B`

`Disk 0` looks like my SSD, `Disk 1` is my Ventoy USB stick?

**Comment by steve6375** [comment]
so what do the log files say?
Use Notepad and have a look.
Search for the word 'error'

**Comment by lmcorr** [comment]
`Error [0x060555] IBS Callback_Productkey_Validate: Error with PidgenX config file while validating product key.`
`Error [0x060555] IBS Callback_Productkey_Validate: An error occurred writing the product key data to the blackboard.`
[both duplicated thrice more]
`Error [0x060126] IBS CallBack_ImageWasSelectedInUi: An error occurred while removing the MultiEdition key from the blackboard. [gle=0x0000069d] IBS GetMachineInfo: Couldn't find info for boot disk [1]`

**Comment by steve6375** [comment]
What exactly is the ISO?
Are you using an XML file at all or anything to do with using a Product Key that you have changed/set?

It does not seem to think that the Product Key or Edition it is trying to install is correct for the system?
Attach  setupact.log file?

**Comment by steve6375** [comment]
P.S. Maybe hard disk is bad. Could you replace it or try installing to a USB HDD and see if that starts to work?

**Comment by lmcorr** [comment]
`Win10_21H2_EnglishInternational_x64.iso`, I've tried an older 190x version as well.

`X: \windows\panther>more setupact.log`
`2022-08-28 09:26:22, Info IBS Installwindows: Successfully loaded resource language [en-gb]`
`2022-08-28 09:26:22, Info [0x0601c1] IBS InstallWindows: Install Path = X:\Sources`
`2022-08-28 09:26:22, Info [0x0601c2] IBS InstallWindows: Setup Phase = 2`
`2022-08-28 09:26:22, Info [0x0601cc] ISB  LogBootDeviceInfo: The firmware boot device ARC path is [multi(0)disk(0)rdisk(2)partition(1) and NT path is [].`
`2022-08-28 09:26:22, Info [0x0601c2] IBS LogBootDeviceInfo: The system boot device ARC path is [ramdisk(0)] and NT path is [\Device\Ramdisk{d9b257fc-684e-4dcb-ab79-03cfa2f6b750}].`
`2022-08-28 09:26:22, Info [0x0601e9] IBS CheckWinPEVersion: Compatible WinPE Version 10.0.19041 sp 0.0`
`2022-08-28 09:26:22, Info [0x0601c9] IBS InstallWindows:Starting a new install from WinPE`
`2022-08-28 09:26:22, Info [0x0606cc] IBS DeletePath: Attempting to delete [X:\windows\panther] (final path [\\?\Volume{d9b257fc-684e-4dcb-ab79-03cfs2f6b750}\Windows\panther]).`
`2022-08-28 09:26:22, Info IBS InstallWindows: Setup working directory = X:\windows\panther`
`2022-08-28 09:26:22, Info [0x0601ce] IBS Setup has started phase 2 at 2022-08-28 09:26:22`
`2022-08-28 09:26:22, Info [0x0601cf] IBS Install source is X:\Sources`
`2022-08-28 09:26:22, Info [0x0601d0] IBS Build version is 10.0.19041.117 (WinBuild.160101.0800)`
`2022-08-28 09:26:22, Info [0x06403f] IBSLIB CreateSetupBlackboard:Creating a new persistent blackboard. Path is [X:\windows\panther\SetupInfo] Setup phase is [2]`
`2022-08-28 09:26:22, Info [0x090008] PANTHR Blackboard::Open: X\windows\panther\SetupInfo succeeded.`
`2022-08-28 09:26:22, Info [0x064043] IBSLIB CreateSetupBlackboard: Successfuly created/opened Setup black board path is [X:\windows\panther\SetupInfo]`
`2022-08-28 09:26:22, Info IBS InstallWindows: No UI language from a pervious boot was found on the blackboard. Using selected language [en-gb].`
`2022-08-28 09:26:22, Info IBS InstallWindows: Setup architecture is [x64]`
`2022-08-28 09:26:22, Info [0x0601d5] IBS InstallWindows: Starting with Empty Queue. Setup Phase = 2`
`2022-08-28 09:26:22, Info PANTHR InitializedCriticalSection for pExecQueue->csLock;`
`2022-08-28 09:26:22, Info PANTHR InitializeModule: Initializing ExecQueue->csLock;`
`2022-08-28 09:26:22, Info PANTHR InitializeModule: Initializing ExecQueue->csLock;`
`2022-08-28 09:26:22, Info [0x0601a4] IBS LoadWorkerModules:Successfully added worker module ScenarioDetect in w-- more (1%) --`

**Comment by lmcorr** [comment]
Tried Windows 10 Media Creation Tool instead and sailed through without a hitch, so looks like this may be something localised to Ventoy.

**Comment by ventoy** [comment]
"Overflow is detected" is fixed in 1.0.80

**Comment by MightyZizz** [comment]
> What happen if you press `ctrl+i` firstly and then select the ISO file to boot.

even I tryed this but it ended up just bringing up a black screen with a blinking cursor which has red and Gray line behind them. please help me.

**Comment by MightyZizz** [comment]
> What happen if you press `ctrl+i` firstly and then select the ISO file to boot.

I tryed this but then it ending up giving me a black screen with a blinking cursor on it which had red and Gray lines in the back ground

**Comment by Inqurity** [comment]
Still have this issue. `ctrl+i` brings up the same blinking cursor, `ctrl+w` boots, but `We couldn't create a new partition or locate an existing one. For more information, see the Setup log files.`

**Comment by DUB1401** [comment]
I also have this problem. Anyone done it?
